########## EDIT REQUIRED ##########

# GPT SETTINGS #
# Get your api key from openai. Remember google/bing is always your best friend.
# Model names: gpt-4-turbo-preview, gpt-3.5-turbo, etc.
# Recommend -> gpt-4-turbo (Better performance, more expensive), gpt-4-o (Good performance, cheaper)

API_KEY: "" # Free API Key with GPT-4 access: https://github.com/CubeGPT/.github/discussions/1
BASE_URL: "https://api.openai.com/v1"

GENERATE_MODEL: "gpt-4-turbo" # Don't use gpt-4, because this model is longer supports json modes.

FORCE_DISABLE_JSON_MODE: True # For openai-formatting claude users.

# ADVANCED MODE #
# This mode is experimental. This will enrich the aesthetics of the generated structure, but may affect the quality of the output to some extent. It also consumes more tokens when this mode is turned on, but we still recommend turning it on.
ADVANCED_MODE: False # Not recommend.
IMAGE_GENERATION_MODEL: "dall-e-3"
IMAGE_SIZE: "1024x1024"
VISION_MODEL: "gpt-4-vision-preview"

# Note: If you are using the free API key we provided, you can't use the advanced mode since it doesn't support dall-e-3 and gpt-4-vision-preview models.
USE_DIFFERENT_APIKEY_FOR_DALLE_MODEL: False
DALLE_API_KEY: ""
DALLE_BASE_URL: "https://api.openai.com/v1"

USE_DIFFERENT_APIKEY_FOR_VISION_MODEL: False
VISION_API_KEY: ""
VISION_BASE_URL: "https://api.openai.com/v1"


########## EDIT OPTIONAL ##########

# EXPERIMENTAL FEATURES #
NAMING_MODEL: "gpt-3.5-turbo"
RENDERING_URL: "https://beta.cubical.xyz/" # Don't change this unless you know what you are doing.

# This will provide GPT the usable block id list
# Befinits: Avoids gpt from generating invalid block ids
# Disadvantages: Costs more (+$0.016 per gen for gpt-4-turbo-2024-04-09, +0.008 for gpt-4o)
GIVE_GPT_BLOCK_ID_LIST: False

# DEVELOPER SETTINGS #
DEBUG_MODE: False
VERSION_NUMBER: "2.0.0" #NEVER EDIT THIS IF YOU DON'T KNOW WHAT ARE YOU DOING

# PROMPT SETTINGS #
# If you don't know what it is, please don't touch it. Be sure to backup before editing.

## Structure Generation ##
SYS_GEN: | 
  You are a minecraft structure builder bot. You should design a building or a structure based on user's instructions.
  You operate in a 3D Space. You work in a X,Y,Z coordinate system. X denotes width, Y denotes depth, Z denotes height.
  Response in json like this:
  {"structures":[{"block":"minecraft:oak_planks","type":"fill","x":0,"y":0,"z":0,"toX":4,"toY":0,"toZ":4},{"block":"minecraft:oak_log","type":"fill","x":1,"y":1,"z":1,"toX":3,"toY":1,"toZ":1},{"block":"minecraft:minecraft:oak_door[half=lower]","type":"setblock","x":2,"y":0,"z":0},{"block":"minecraft:birch_sign","type":"setblock","x":2,"y":1,"z":0},{"block":"minecraft:oak_fence","type":"fill","x":0,"y":1,"z":2,"toX":0,"toY":1,"toZ":4},{"block":"minecraft:oak_fence","type":"fill","x":1,"y":1,"z":4,"toX":5,"toY":1,"toZ":4},{"block":"minecraft:oak_fence","type":"fill","x":5,"y":1,"z":3,"toX":5,"toY":1,"toZ":1}]}
  Never response anything else. The schematic can be as large as 25*25*50 or even bigger. Never use markdown format. Use \n for line feed.

USR_GEN: | 
  %DESCRIPTION%

SYS_GEN_NAME: |
  Give a name to the building based on user's desciption. Do not use spaces.
  For example:
  Input "A small house with a red roof."
  Output "RedRoofHouse"

  Input "A cafe with a modern design."
  Output "ModernCafe"

USR_GEN_NAME: |
  %DESCRIPTION%

## Advanced Mode ##

### Programme ###
BTR_DESC_SYS_GEN: |
  You are an minecraft schematic designer. Your role is to design a programme based on the requirements sent to you by the user.
  For exmaple,
  User input: "A cafe."
  Response: "A small cafe with a modern design, red roof and brown door, big windows. Inside, there's two tables and a bar."

BTR_DESC_USR_GEN: |
  %DESCRIPTION%

### Image Tag Generation ###
IMG_TAG_SYS_GEN: |
  You work for a minecraft schematic company and you need to use AI to generate the design image based on designer's architectural programme. Please response the tags you'd like to use for the image generation.
  Never response anything else.
  Example resposne: "A minecraft building with a modern design, red roof and brown door, big windows."

IMG_TAG_USR_GEN: |
  Designer's programme: %PROGRAMME%

### Stucture Generation (Advanced with gpt-4-vision) ###
SYS_GEN_ADV: |
  You are a minecraft structure builder bot. You should design a building or a structure based on designer's architectural programme AND the design image.
  You operate in a 3D Space. You work in a X,Y,Z coordinate system. X denotes width, Y denotes depth, Z denotes height.
  Response in json like this:
  {"structures":[{"block":"minecraft:oak_planks","type":"fill","x":0,"y":0,"z":0,"toX":4,"toY":0,"toZ":4},{"block":"minecraft:oak_log","type":"fill","x":1,"y":1,"z":1,"toX":3,"toY":1,"toZ":1},{"block":"minecraft:minecraft:oak_door[half=lower]","type":"setblock","x":2,"y":0,"z":0},{"block":"minecraft:birch_sign","type":"setblock","x":2,"y":1,"z":0},{"block":"minecraft:oak_fence","type":"fill","x":0,"y":1,"z":2,"toX":0,"toY":1,"toZ":4},{"block":"minecraft:oak_fence","type":"fill","x":1,"y":1,"z":4,"toX":5,"toY":1,"toZ":4},{"block":"minecraft:oak_fence","type":"fill","x":5,"y":1,"z":3,"toX":5,"toY":1,"toZ":1}]}
  Never response anything else. Do not design a building which is too large (more than 10 floors). Never use markdown format. Use \n for line feed.

USR_GEN_ADV: |
  %DESCRIPTION%
  The image is attached below.
