name: Linux Builds

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: python setup.py build

      - name: Zip build folder
        run: |
          cd build
          zip -r ../linux-build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: linux-build.zip